Generate Pokemon header files using json and inja
pret/pokefirered pull request #369
Opened 2020-11-11 16:10 UTC by V-FEXrt

The PR makes it so that many of the pokemon data header files are generated from json. This is a checkpoint towards a larger goal of allowing any given pokemon to be defined fully by a single json file. The end goal would be allowing the creation/deletion of a pokemon from the game engine by simply adding or removing a json file (scripts that depend on a given pokemon are unchanged). Doing this makes it easier to manipulate pokemon either by manually editing the json or by writing a tool that understands the json.

Pokemon that have game version variants (dugtrio and deoxys) have two files, one for each version, and are handled by adding a `"game_variant": "FIRERED"` key to the json.

**Major changes**
- json file for each pokemon is introduced under `data/pokemon`
- The following files are now generated at build time and removed from the repo 
  - src/data/pokemon/base_stats.h
  - src/data/pokemon/egg_moves.h
  - src/data/pokemon/evolution.h
  - src/data/pokemon/level_up_learnsets.h
  - src/data/pokemon/level_up_learnset_pointers.h
  - src/data/pokemon/tmhm_learnsets.h
  - src/data/pokemon/tutor_learnsets.h
- The build now depends on the [shell tool jq](https://stedolan.github.io/jq/)

2020-11-11 18:11 UTC, PikalaxALT requested changes

2020-11-11 18:11 UTC, PikalaxALT commented on json_data_rules.mk
> +	$(JSONPROC) $^ $@
These can probably be simplified.

```makefile
POKEMON_JSON_HEADERS := $(DATA_C_SUBDIR)/pokemon/level_up_learnset_pointers.h $(DATA_C_SUBDIR)/pokemon/level_up_learnsets.h ...

AUTO_GEN_TARGETS += $(POKEMON_JSON_HEADERS)
GENERATED_HEADERS += $(POKEMON_JSON_HEADERS)

$(POKEMON_JSON_HEADERS): $(DATA_C_SUBDIR)/%.h: $(DATA_ASM_SUBDIR)/pokemon/pokemon_list.json $(DATA_ASM_SUBDIR)/%.inja
    $(JSONPROC) $^ $@

2020-11-11 18:44 UTC, V-FEXrt commented on json_data_rules.mk
> +	$(JSONPROC) $^ $@
Done!

2020-11-11 20:27 UTC, PikalaxALT approved these changes

2020-11-11 21:12 UTC, GriffinRichards commented
I think my response to <https://github.com/pret/pokeemerald/pull/1123> applies similarly here in that I wonder if this is the kind of thing that's better left as a fork. I understand that this is meant to be a step towards making incrementally adding pokemon easier, but A. I don't think this even addresses the most annoying parts of that process, and B. a pokemon editor tool sounds like the kind of thing that's going to break easily, given the sorts of deviating changes people are likely to make. There's also some things that are going to be messy to extract. There's a bunch of miscellaneous tables indexed by species that people are going to need to update anyway, and people are likely to add more tables of their own.

2020-11-13 05:17 UTC, V-FEXrt commented
Closing per discussion in discord.

2020-11-13 05:17 UTC, closed without merging