Port UBFIX Macro and Some Usages from Emerald
pret/pokefirered pull request #445
Opened 2021-06-27 02:56 UTC by Kurausukun

Includes the save fix on modern -O3. These are just things I tried while fixing the other issue, but they should probably be ported either way.

2021-07-01 18:30 UTC, GriffinRichards requested changes

2021-07-01 18:30 UTC, GriffinRichards commented on src/field_effect.c
> +        #endif
Port `SAFE_DIV` from pokeemerald instead

2021-07-03 21:19 UTC, Kurausukun commented on src/field_effect.c
> +        #endif
Done, also ported other usages where applicable

2021-07-03 21:25 UTC, GriffinRichards approved these changes

2021-07-03 21:25 UTC, merged